### ISSUE TITLE
Valid token is not being verified correctly

### ISSUE THREAD

**Issue by masbaehr** [frankleng/cloudflare-cognito-jwt-verifier#1]
I'm trying to verify a valid 'access' type token, but also tried with 'id'

Getting this issue:
```
Error
    at new JwtInvalidError2 (worker.js:4064:24)
    at verify (worker.js:4168:21)
    at verifyAuth (worker.js:4230:20)
    at handleRequest (worker.js:4242:24)
    at worker.js:4236:23
```

Any idea what could be wrong?

**Comment by frankleng** [comment]
make sure ur actually getting the token string from header. best to log out all headers and see how they are defined

either the token string is empty, or the decoded payload doesn't have the necessary params
